### ISSUE TITLE
Test your stuff

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#11]
Your code seems logical and fine but it's not tested. Make a simple implementation on the frontend that displays x, y, angle and stuff, and create some event listeners that listen to keypress and keyrelease events on the page.

**Comment by igabesz** [comment]
You may do this from whithin Angular or from native JS. In the latter case please make the SocketService available for native JS too, e.g. add a constructor, and: `window.SocketService = this;`

**Comment by csutorasa** [comment]
Waiting for test environment to be merged into development

**Comment by csutorasa** [comment]
Finally I could test collision detection, it had some serious issues, but it seems like it is bugfree now.
