### ISSUE TITLE
Players can join rooms through WS

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#13]
Specify and create a way for players to connect to the game. This may happen through a special message OR during authenticating (by a [custom middleware](http://socket.io/docs/server-api/#namespace#use%28fn:function%29:namespace)). In the latter case you might send the roomId as a query parameter. 

This has lots of subquestions, feel free to discuss them here or to create new issues.

**Comment by csutorasa** [comment]
Players can join rooms through WS, frontend issues will be solved in a different issue.
