### ISSUE TITLE
Specify projectiles

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#14]
Make a specification about possible projectiles in the game, about the physics it requires, implementation proposals, etc. This is not the coding part yet.

**Comment by csutorasa** [comment]
I specified projectiles, but they are not functional yet. Players are unable to shoot it, but the definitions and the simulation is updated.

**Comment by igabesz** [comment]
Cool. A testing environment is essential here too to check the implementation.

**Comment by csutorasa** [comment]
Projectile creation and collision detection added.
