### ISSUE TITLE
Physics on server and client

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#23]
Choose a way to implement physics (inc. bounding rects, collisions, velocity and acceleration) and prepare it for both client and server side implementation. The server calculates the reliable physics -- but because of the delay the clients should also make their own calculations. These may utilize the capabilities of the frontend GUI lib.

**Comment by igabesz** [comment]
@annakolozsvari We're looking forward to hear the capabilities of Phaser.

**Comment by igabesz** [comment]
@csutorasa How is this issue? Thinking about milestones: bounding rects are not necessary for v0.1, if it's not ready we can put them into a separate issue and close this.

**Comment by csutorasa** [comment]
I think the physics is in sync between the client and the server now.
