### ISSUE TITLE
Player characters death

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#24]
Prepare the backend that the player characters may die.

**Comment by igabesz** [comment]
What happens next? Going back to the room and ship selector page?

**Comment by igabesz** [comment]
We've got a basic health system, now we have to decide what happens when it reaches zero. 

@csutorasa @dani-mezo @annakolozsvari all ideas are welcome!

**Comment by csutorasa** [comment]
When a player dies we agreed to put them back to room select screen. This is a the current logic, but can be changed in the future.
