### ISSUE TITLE
Health system

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#25]
Ships have health, if health goes to zero then player character dies, see #24. Ships may have different max healths. Examine the possibilities of health gain and loss.

**Comment by csutorasa** [comment]
Basic health system is added.

**Comment by igabesz** [comment]
What happens when health goes to zero?

**Comment by csutorasa** [comment]
It has no effect so far, and added with TO-DO in code. I think it is an issue I need to decide with the team.

**Comment by igabesz** [comment]
@csutorasa I mark this issue closed, the rest should be done in #24
