### ISSUE TITLE
Login refactored

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#30]
The current login solution has issues. Use separate pages, less dynamic content loading, more redirecting. Redirects should be done on server-side. We don't need the frame stuff right now.

**Comment by csutorasa** [comment]
With the available JQuery code it seemed to be easier to implement with a static frame and dynamic content. However if the route authorization and full angular support will be implemented frame system can be removed.

**Comment by igabesz** [comment]
Fine by me, let's use full-featured Angular!

**Comment by dani-mezo** [comment]
With csutorasa's help, I got understood more of the angular magic than ever could be imagined. Login can be refactored in a week now, I think.
