### ISSUE TITLE
Keypress events are buggy

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#32]
The key pressed and released state should be stored per button. One common keyrelease stuff is not enough, e.g.
- press key 1
- press key 2
- release key 1
- --> key 2 is still pressed!

**Comment by igabesz** [comment]
Try to solve this before #1 is finished

**Comment by madbence** [comment]
some ideas: https://github.com/madbence/spacegame/blob/master/src/client/lib/keypress.js
usage: https://github.com/madbence/spacegame/blob/master/src/client/app.js#L57-L74

:wink:

**Comment by igabesz** [comment]
Thanks! :cool:

**Comment by annakolozsvari** [comment]
I think the new implementation solves this.
