### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#6]
Create a user management system in the backend using MongoDB and a REST register & login API that can be called from the client. Modify the README.md and document MongoDB setup

**Comment by igabesz** [comment]
Start thinking about a player settings and an Achievements system as well, it will be a task quite soon.

**Comment by dani-mezo** [comment]
Login/sign up is implemented.
Note: Imo index.html should be only served if the client authenticated itself, not by default from the public folder.
