### ISSUE TITLE
Basic graphics to frontend

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#7]
Get some very basic images for the frontend lib. E.g. a spaceship, etc. Think about how to store them, where to put them (somewhere in the public folder OR create a new folder for them -- and make it publicly available through Express?)

**Comment by igabesz** [comment]
Any help wanted? @annakolozsvari

**Comment by igabesz** [comment]
@annakolozsvari you can close your issues if you feel you're done with them

**Comment by annakolozsvari** [comment]
Still looking for other spaceships, since there'll be more players.

**Comment by igabesz** [comment]
We can use the same image for the other players too. Further spaceship images will be required when there will be more available ships.
