### ISSUE TITLE
removeAllListeners removes ALL event listeners

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#9]
And so no events are processed after this is called. E.g. when someone disconnects. 

This function does not take a parameter. You need another solution for this.

**Comment by csutorasa** [comment]
It was a working solution, but the tsd is outdated a bit. Fixed with a solution, that is supported by our tsd.

**Comment by igabesz** [comment]
It seems true... anyway, I check this error again, and you might add a pull-request to the tsd library containing this fix.
